### PR TITLE
backdrop image from local file

### PR DESCRIPTION
**Pull request by kittinan**
- allow a user to change backdrop image from local file

Screenshot-Hacktoberfest Design Generator - Google Chrome

### CODE REVIEW

**Comment by heypoom** [comment]
Looks great! Thank you 💯

**Comment by heypoom** [comment]
There is a merge conflict with main branch. could you please resolve that? Thank you 🙏

**Comment by kittinan** [comment]
@phoomparin fixed

**Comment by heypoom** [comment]
Thank you krub! 🎉

**Pull request merged**
